import type { Tile } from '@bookbingo/lib-types';

export const TILES: Tile[] = [
  { id: 't01', name: 'unfinished reread' },
  { id: 't02', name: 'part of a series' },
  { id: 't03', name: '1000+ pages' },
  { id: 't04', name: 'under 100 pages' },
  { id: 't05', name: 'graphic novel or cookbook' },
  { id: 't06', name: 'biography or autobiography' },
  { id: 't07', name: 'based on a true story' },
  { id: 't08', name: 'nonfiction about nature' },
  { id: 't09', name: 'nonfiction about a hobby' },
  { id: 't10', name: 'nonfiction travelogue' },
  { id: 't11', name: 'translated to english' },
  { id: 't12', name: 'poetry by a person of color' },
  { id: 't13', name: 'fiction with queer protagonist' },
  { id: 't14', name: 'queer nonfiction' },
  { id: 't15', name: 'author shares your ethnicity' },
  { id: 't16', name: 'owned but unread' },
  { id: 't17', name: 'anthropomorphic non-human protagonist' },
  { id: 't18', name: 'banned book' },
  { id: 't19', name: 'set within 24 hours' },
  { id: 't20', name: 'political ideology' },
  { id: 't21', name: 'dissident movements' },
  { id: 't22', name: 'american history' },
  { id: 't23', name: 'architectural history' },
  { id: 't24', name: 'socially taboo' },
  { id: 't25', name: 'genre classic or foundational text' },
  { id: 't26', name: 'multiple povs' },
  { id: 't27', name: 'well-behaved women rarely make history' },
  { id: 't28', name: 'pre-partition india' },
  { id: 't29', name: 'enemies to lovers' },
  { id: 't30', name: 'about sports' },
  { id: 't31', name: 'adapted to other medium' },
  { id: 't32', name: 'protagonist over 50' },
  { id: 't33', name: 'shakespeare play' },
  { id: 't34', name: 'non-western-inspired fantasy' },
  { id: 't35', name: "children's book" },
  { id: 't36', name: 'smut' },
  { id: 't37', name: 'published in birth year' },
  { id: 't38', name: 'contrasting read (dialectics)' },
  { id: 't39', name: 'unreliable narrator' },
  { id: 't40', name: 'breaks the 4th wall' },
  { id: 't41', name: 'espionage or intelligence' },
  { id: 't42', name: 'interactive or nonlinear format' },
  { id: 't43', name: 'time travel' },
  { id: 'm01', name: "from someone else's 2025 list" },
  { id: 'm02', name: 'recommended by librarian or bookstore' },
  { id: 'm03', name: 'spotted someone reading in the wild' },
  { id: 'm04', name: 'based solely on a recommendation' },
  { id: 'm05', name: 'from 2026 awards list' },
  { id: 'm06', name: 'inspiration of 2 favorite authors' },
];
