import type { Tile } from '@bookbingo/lib-types';

export const TILES: Tile[] = [
  { id: 't01', name: 'unfinished reread', isManual: false },
  { id: 't02', name: 'part of a series', isManual: false },
  { id: 't03', name: '1000+ pages', isManual: false },
  { id: 't04', name: 'under 100 pages', isManual: false },
  { id: 't05', name: 'graphic novel or cookbook', isManual: false },
  { id: 't06', name: 'biography or autobiography', isManual: false },
  { id: 't07', name: 'based on a true story', isManual: false },
  { id: 't08', name: 'nonfiction about nature', isManual: false },
  { id: 't09', name: 'nonfiction about a hobby', isManual: false },
  { id: 't10', name: 'nonfiction travelogue', isManual: false },
  { id: 't11', name: 'translated to english', isManual: false },
  { id: 't12', name: 'poetry by a person of color', isManual: false },
  { id: 't13', name: 'fiction with queer protagonist', isManual: false },
  { id: 't14', name: 'queer nonfiction', isManual: false },
  { id: 't15', name: 'author shares your ethnicity', isManual: false },
  { id: 't16', name: 'owned but unread', isManual: false },
  { id: 't17', name: 'anthropomorphic non-human protagonist', isManual: false },
  { id: 't18', name: 'banned book', isManual: false },
  { id: 't19', name: 'set within 24 hours', isManual: false },
  { id: 't20', name: 'political ideology', isManual: false },
  { id: 't21', name: 'dissident movements', isManual: false },
  { id: 't22', name: 'american history', isManual: false },
  { id: 't23', name: 'architectural history', isManual: false },
  { id: 't24', name: 'socially taboo', isManual: false },
  { id: 't25', name: 'genre classic or foundational text', isManual: false },
  { id: 't26', name: 'multiple povs', isManual: false },
  {
    id: 't27',
    name: 'well-behaved women rarely make history',
    isManual: false,
  },
  { id: 't28', name: 'pre-partition india', isManual: false },
  { id: 't29', name: 'enemies to lovers', isManual: false },
  { id: 't30', name: 'about sports', isManual: false },
  { id: 't31', name: 'adapted to other medium', isManual: false },
  { id: 't32', name: 'protagonist over 50', isManual: false },
  { id: 't33', name: 'shakespeare play', isManual: false },
  { id: 't34', name: 'non-western-inspired fantasy', isManual: false },
  { id: 't35', name: "children's book", isManual: false },
  { id: 't36', name: 'smut', isManual: false },
  { id: 't37', name: 'published in birth year', isManual: false },
  { id: 't38', name: 'contrasting read (dialectics)', isManual: false },
  { id: 't39', name: 'unreliable narrator', isManual: false },
  { id: 't40', name: 'breaks the 4th wall', isManual: false },
  { id: 't41', name: 'espionage or intelligence', isManual: false },
  { id: 't42', name: 'interactive or nonlinear format', isManual: false },
  { id: 't43', name: 'time travel', isManual: false },
  { id: 'm01', name: "from someone else's 2025 list", isManual: true },
  { id: 'm02', name: 'recommended by librarian or bookstore', isManual: true },
  { id: 'm03', name: 'spotted someone reading in the wild', isManual: true },
  { id: 'm04', name: 'based solely on a recommendation', isManual: true },
  { id: 'm05', name: 'from 2026 awards list', isManual: true },
  { id: 'm06', name: 'inspiration of 2 favorite authors', isManual: true },
];
