export const TILES = [
  { id: 't01', name: "reread a book you didn't finish", isManual: false },
  { id: 't02', name: 'part of a series', isManual: false },
  { id: 't03', name: '1000+ pages', isManual: false },
  { id: 't04', name: 'under 100 pages', isManual: false },
  { id: 't05', name: 'a graphic novel or cookbook', isManual: false },
  { id: 't06', name: 'biography or auto-biography', isManual: false },
  { id: 't07', name: 'based on a true story', isManual: false },
  { id: 't08', name: 'nonfiction book about nature', isManual: false },
  { id: 't09', name: 'nonfiction on a hobby', isManual: false },
  { id: 't10', name: 'nonfiction travelogue', isManual: false },
  { id: 't11', name: 'a book that was translated to english', isManual: false },
  { id: 't12', name: 'poetry by a person of color', isManual: false },
  { id: 't13', name: 'fiction w/ queer protagonist(s)', isManual: false },
  { id: 't14', name: 'queer non-fiction', isManual: false },
  { id: 't15', name: 'author same ethnicity as yourself', isManual: false },
  { id: 't16', name: "already own but haven't read / been wanting to read for a long time", isManual: false },
  { id: 't17', name: 'anthropomorphic non-humanoid main character', isManual: false },
  { id: 't18', name: 'banned book', isManual: false },
  { id: 't19', name: 'a book that takes place within 24 hours', isManual: false },
  { id: 't20', name: 'political ideology', isManual: false },
  { id: 't21', name: 'dissident movements', isManual: false },
  { id: 't22', name: 'about american history', isManual: false },
  { id: 't23', name: 'architecture history', isManual: false },
  { id: 't24', name: 'Contextually social taboo', isManual: false },
  { id: 't25', name: 'a cliche/foundational book of a genre', isManual: false },
  { id: 't26', name: 'multiple POVs', isManual: false },
  { id: 't27', name: 'well behaved women rarely make history', isManual: false },
  { id: 't28', name: 'based in india pre-partition', isManual: false },
  { id: 't29', name: 'enemies to lovers', isManual: false },
  { id: 't30', name: 'book about sports', isManual: false },
  { id: 't31', name: 'made into a movie show or game', isManual: false },
  { id: 't32', name: 'main character older than 50', isManual: false },
  { id: 't33', name: 'shakespeare play', isManual: false },
  { id: 't34', name: 'fantasy inspired by non-western culture', isManual: false },
  { id: 't35', name: 'childrens book', isManual: false },
  { id: 't36', name: 'smut', isManual: false },
  { id: 't37', name: 'published the year you were born', isManual: false },
  { id: 't38', name: 'book read in contrast to another', isManual: false },
  { id: 't39', name: 'unreliable narrator', isManual: false },
  { id: 't40', name: 'breaks the 4th wall', isManual: false },
  { id: 't41', name: 'book about espionage or intelligence', isManual: false },
  { id: 't42', name: 'Interactive/nonlinear book (nonlinear reading order not nonlinear storytelling order)', isManual: false },
  { id: 't43', name: 'Time travel', isManual: false },
  { id: 'm01', name: "read a book from someone else's 2025 list", isManual: true },
  { id: 'm02', name: 'recommended by a librarian or bookstore', isManual: true },
  { id: 'm03', name: 'saw someone reading in the wild', isManual: true },
  { id: 'm04', name: 'read a book solely based a recommendation', isManual: true },
  { id: 'm05', name: 'from 2026 awards list', isManual: true },
  { id: 'm06', name: 'author named as an inspiration of 2 favorite authors', isManual: true },
];