export const TILES = [
  // Book-Assignable Tiles (43)
  { id: 't01', name: 'A Book with More Than 500 Pages', isManual: false },
  { id: 't02', name: 'A Romance Novel', isManual: false },
  { id: 't03', name: 'A Book That Became a Movie', isManual: false },
  { id: 't04', name: 'A Book Published This Year', isManual: false },
  { id: 't05', name: 'A Book with a Number in the Title', isManual: false },
  { id: 't06', name: 'A Book Written by Someone Under 30', isManual: false },
  { id: 't07', name: 'A Book with Non-Human Characters', isManual: false },
  { id: 't08', name: 'A Funny Book', isManual: false },
  { id: 't09', name: 'A Book by a Female Author', isManual: false },
  { id: 't10', name: 'A Book with a Mystery', isManual: false },
  { id: 't11', name: 'A Book with a One-Word Title', isManual: false },
  { id: 't12', name: 'A Book of Short Stories', isManual: false },
  { id: 't13', name: 'A Book Set in a Different Country', isManual: false },
  { id: 't14', name: 'A Non-Fiction Book', isManual: false },
  { id: 't15', name: 'The First Book by a Favorite Author', isManual: false },
  { id: 't16', name: 'A Book You Heard About Online', isManual: false },
  { id: 't17', name: 'A Best-Selling Book', isManual: false },
  { id: 't18', name: 'A Book with a Blue Cover', isManual: false },
  { id: 't19', name: 'A Book of Poetry', isManual: false },
  { id: 't20', name: 'A Book Set in the Future', isManual: false },
  { id: 't21', name: 'A Book About a Historical Event', isManual: false },
  { id: 't22', name: 'A Book with a Love Triangle', isManual: false },
  { id: 't23', name: 'The First Book in a Series', isManual: false },
  { id: 't24', name: 'A Book with a Badass Heroine', isManual: false },
  { id: 't25', name: 'A Book That Makes You Cry', isManual: false },
  { id: 't26', name: 'A Book with Magic', isManual: false },
  { id: 't27', name: 'A Graphic Novel', isManual: false },
  { id: 't28', name: "A Book by an Author You'll Never Read Before", isManual: false },
  { id: 't29', name: 'A Book You Own but Haven\'t Read', isManual: false },
  { id: 't30', name: 'A Book Set in Your Hometown', isManual: false },
  { id: 't31', name: 'A Book Written in the 20th Century', isManual: false },
  { id: 't32', name: 'A Book with a Travel Theme', isManual: false },
  { id: 't33', name: 'A Book with a Character Who Has Your Name', isManual: false },
  { id: 't34', name: 'A Book with a Mostly Black Cover', isManual: false },
  { id: 't35', name: 'A Memoir or Autobiography', isManual: false },
  { id: 't36', name: 'A Book with a Coming-of-Age Story', isManual: false },
  { id: 't37', name: 'A Book Set in a School', isManual: false },
  { id: 't38', name: 'A Book by a POC Author', isManual: false },
  { id: 't39', name: 'A Book Published in the Month of Your Birthday', isManual: false },
  { id: 't40', name: 'A Book with a Family Saga', isManual: false },
  { id: 't41', name: 'A Book with a Protagonist Over 60', isManual: false },
  { id: 't42', name: 'A Book with an LGBTQ+ Protagonist', isManual: false },
  { id: 't43', name: 'A Book of Essays', isManual: false },

  // Manual Tiles (6)
  { id: 'm01', name: 'Attend a Book Club Meeting', isManual: true },
  { id: 'm02', name: 'Visit a New Library or Bookstore', isManual: true },
  { id: 'm03', name: 'Post a Book Review Online', isManual: true },
  { id: 'm04', name: 'Listen to an Audiobook', isManual: true },
  { id: 'm05', name: 'Read a Book in a Single Day', isManual: true },
  { id: 'm06', name: 'Organize Your Bookshelf', isManual: true },
];
